export interface TaskImage {
  /**
   * Original image stored in S3 originals bucket.
   */
  originalBucket: string;
  originalKey: string;

  /**
   * Version ID is important because old versions must be retained in S3.
   */
  originalVersionId?: string;

  /**
   * Resized image/thumbnail generated by Lambda.
   */
  resizedBucket?: string;
  resizedKey?: string;

  fileName: string;
  mimeType: string;
  sizeBytes: number;

  uploadedBy: string;
  uploadedAt: string;

  /**
   * Used when image is replaced/deleted from the task view.
   * Old S3 object versions remain in S3.
   */
  isActive: boolean;
}